title: SaBa Art Gallery
description: "Persian calligraphy & modern abstract art by SaBa. An online art gallery for unique artworks, artists, and collectors worldwide."
baseurl: ""
url: "https://sabapersiancalligraphy.com"

permalink: pretty
markdown: kramdown

collections:
  artworks:
    output: true
  blogs:
    output: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      sitemap: true

  - scope:
      path: ""
      type: "404"
    values:
      sitemap: false
