# =========================
# Build (Jekyll)
# =========================
[build]
  command = "bundle exec jekyll build"
  publish = "_site"

# =========================
# Redirects → canonical domain
# Primary: https://sabapersiancalligraphy.com
# =========================
# Primary HTTP → HTTPS
[[redirects]]
from = "http://sabapersiancalligraphy.com/*"
to   = "https://sabapersiancalligraphy.com/:splat"
status = 301
force  = true

# Primary www → apex
[[redirects]]
from = "https://www.sabapersiancalligraphy.com/*"
to   = "https://sabapersiancalligraphy.com/:splat"
status = 301
force  = true

[[redirects]]
from = "http://www.sabapersiancalligraphy.com/*"
to   = "https://sabapersiancalligraphy.com/:splat"
status = 301
force  = true

# Aliases: abstractartsaba.com → primary
[[redirects]]
from = "http://abstractartsaba.com/*"
to   = "https://sabapersiancalligraphy.com/:splat"
status = 301
force  = true

[[redirects]]
from = "https://abstractartsaba.com/*"
to   = "https://sabapersiancalligraphy.com/:splat"
status = 301
force  = true

[[redirects]]
from = "http://www.abstractartsaba.com/*"
to   = "https://sabapersiancalligraphy.com/:splat"
status = 301
force  = true

[[redirects]]
from = "https://www.abstractartsaba.com/*"
to   = "https://sabapersiancalligraphy.com/:splat"
status = 301
force  = true

# Aliases: sabaartgallery.com → primary
[[redirects]]
from = "http://sabaartgallery.com/*"
to   = "https://sabapersiancalligraphy.com/:splat"
status = 301
force  = true

[[redirects]]
from = "https://sabaartgallery.com/*"
to   = "https://sabapersiancalligraphy.com/:splat"
status = 301
force  = true

[[redirects]]
from = "http://www.sabaartgallery.com/*"
to   = "https://sabapersiancalligraphy.com/:splat"
status = 301
force  = true

[[redirects]]
from = "https://www.sabaartgallery.com/*"
to   = "https://sabapersiancalligraphy.com/:splat"
status = 301
force  = true

# Netlify subdomain → primary
[[redirects]]
from = "https://hilarious-bonbon-1bffcc.netlify.app/*"
to   = "https://sabapersiancalligraphy.com/:splat"
status = 301
force  = true

# (optional) http version of netlify subdomain
[[redirects]]
from = "http://hilarious-bonbon-1bffcc.netlify.app/*"
to   = "https://sabapersiancalligraphy.com/:splat"
status = 301
force  = true


# =========================
# Security & performance headers
# =========================
[[headers]]
for = "/*"
  [headers.values]
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  X-Frame-Options = "SAMEORIGIN"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"

  # CSP (loose enough for your current stack: Tailwind CDN, Alpine, GFonts, GCS images, reCAPTCHA, GA)
  # Tighten later if you move away from inline/JS CDN.
  Content-Security-Policy = """
    default-src 'self';
    img-src 'self' https://storage.googleapis.com https://www.google-analytics.com data:;
    script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://www.google.com https://www.gstatic.com https://www.googletagmanager.com;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
    font-src 'self' https://fonts.gstatic.com data:;
    connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://www.googletagmanager.com;
    frame-src 'self' https://www.google.com;
    base-uri 'self';
    frame-ancestors 'self'
  """

# Long cache for versioned static assets under /assets/
[[headers]]
for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# HTML should revalidate
[[headers]]
for = "/*.html"
  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"

# Optional: sitemap/robots explicit caching
[[headers]]
for = "/sitemap.xml"
  [headers.values]
  Cache-Control = "public, max-age=3600"

[[headers]]
for = "/robots.txt"
  [headers.values]
  Cache-Control = "public, max-age=3600"
