[[redirects]]
from = "https://abstractartsaba.com/*"
to = "https://sabapersiancalligraphy.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://sabaartgallery.com/*"
to = "https://sabapersiancalligraphy.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://hilarious-bonbon-1bffcc.netlify.app/*"
to = "https://sabapersiancalligraphy.com/:splat"
status = 301
force = true
